AWSTemplateFormatVersion: 2010-09-09

Description: This template creates an EC2 instance which enables SSH connection. 

Resources:
  GuileCFInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: eklenecek
      InstanceType: t2.micro
      KeyName: eklenecek
      SecurityGroups:
        - eklenecek
      Tags:
        - Key: Name
          Value: guile-cf-instance
      