AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an EC2 instance to run a static website application deployed with Apache Web Server

Parameters:
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Please Enter the EC2 Key Pair to allow HTTP and SSH access to the instances

Resources:
  romanSecGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: SSH + HTTP #required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          
      Tags:
          - Key: Name
            Value: RomanConvertSecGroup
  romanInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-0c94855ba95c71c99
      InstanceType: t2.micro
      KeyName: !Ref KeyPair
      SecurityGroups:
        - !Ref romanSecGroup
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName}
      UserData: 
        Fn::Base64:
          !Sub |
            #!/bin/bash
            yum update -y
            yum install -y python3
            pip3 install flask
            wget https://raw.githubusercontent.com/Anthncara/MEMO/master/aws/projects/001-roman-numerals-converter/appV2.py
            mkdir templates
            cd templates
            wget https://raw.githubusercontent.com/Anthncara/MEMO/master/aws/projects/001-roman-numerals-converter/templates/result.html
            wget https://raw.githubusercontent.com/Anthncara/MEMO/master/aws/projects/001-roman-numerals-converter/templates/index.html
            cd ..
            python3 appV2.py

Outputs:
  WebsiteURL:
    Description: Roman Numerals Converter Application Website URL
    Value: !Join
      - '://'
      - - http
        - !GetAtt romanInstance.PublicDnsName
